version: '3.3'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: mars-rover
    volumes:
      - ./:/app
    command:
      ./console marsrovers:import ./resources/input.txt